# Generated by Django 4.1.7 on 2023-03-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='owner',
        ),
    ]
